### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by ltfschoen** [sogolmalek/EIP-x#4]
from initial review it seems the Rust code includes the following:
- Cargo.toml - dependencies need to be fixed (links to common, consensus, config folders are missing) https://github.com/sogolmalek/EIP-x/blob/main/Client-Rust/Cargo.toml
- RPC.rs - runs Ethereum light client server and exposes JSON RPC endpoints
- client.rs &
  partial view data storage.rs &
  temporary database.rs - connects to Helios JSON RPC URL running Goerli light client using Alchemy SDK and ethers-rs. uses cache and in-memory database to query partial view data for the balance of an account
- libp2p.rs - light client peer discovery
- libp2p::swarm::SwarmBehaviour.rs - polling loop for the swarm, handles p2p connections and messages
-  light_client_protocol.rs &
    Customlibnetwrok.rs - light client message types
- networking loop.rs - run light client and swarm

**Comment by sogolmalek** [comment]
Thank you so much Luke! yeah still need some time to fix the code to be compiled properly, rust is not my strength
